name: publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        electron: ["15", "16", "17", "18", "19", "20"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.4.0'

      - run: npm install electron@${{ matrix.electron }}

      - run: bash ./test.sh
